services:
  webhook:
    image: puzzlemoondev/bililive-recorder-webhook:latest
    ports:
      - '2356:2356'
      - '5555:5555'
      - '9001:9001'
    volumes:
      - ./rec:/rec
      - ./biliup:/etc/biliup
      - ./DanmakuFactory:/etc/DanmakuFactory
      - ./redis_config:/var/lib/redis
      - ./redis_data:/var/redis
      - ./flower_data:/etc/flower
    environment:
      - BREC_HTTP_BASIC_USER=${RECORDER_USER}
      - BREC_HTTP_BASIC_PASS=${RECORDER_PASS}
      - BAIDUPCS_BDUSS
      - BAIDUPCS_STOKEN
      - BAIDUPCS_MAX_UPLOAD_PARALLEL
      - ALIYUNPAN_RTOKEN
      - BURN_DANMAKU
      - DANMAKU_FACTORY_ARGS
      - BILIBILI_UPLOAD_BURNED
      - REMOVE_LOCAL
      - FLOWER_PERSISTENT=True
      - FLOWER_STATE_SAVE_INTERVAL=10000
      - FLOWER_DB=/etc/flower/flower.db
    restart: always
