services:
  webhook:
    # build:
    #   context: .
    #   target: webhook
    image: puzzlemoondev/bililive-recorder-webhook
    ports:
      - '2356:2356'
      - '5555:5555'
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./rec:/rec
      - ./webhook:/webhook
      - ./biliup:/etc/biliup
    environment:
      - RECORDER_USER
      - RECORDER_PASS
      - BAIDUPCS_BDUSS
      - BAIDUPCS_STOKEN
      - ALIYUNPAN_RTOKEN
    restart: always
