services:
  webhook:
    # image: puzzlemoondev/bililive-recorder-webhook:local
    image: puzzlemoondev/bililive-recorder-webhook:latest
    ports:
      - '2356:2356'
      - '5555:5555'
      - '9001:9001'
    volumes:
      - ./rec:/rec
      - ./webhook:/webhook
      - ./biliup:/etc/biliup
    environment:
      - RECORDER_USER
      - RECORDER_PASS
      - BAIDUPCS_BDUSS
      - BAIDUPCS_STOKEN
      - ALIYUNPAN_RTOKEN
    restart: always
