services:
  recorder:
    container_name: recorder
    image: bililive/recorder
    ports:
      - '2356:2356'
    networks:
      - recorder_network
    volumes:
      - ./rec:/rec
    command:
      [
        'run',
        '--bind',
        'http://*:2356',
        '--http-basic-user',
        '${RECORDER_USER}',
        '--http-basic-pass',
        '${RECORDER_PASS}',
        '/rec',
      ]
    restart: always
    depends_on:
      - webhook
  webhook:
    container_name: webhook
    # build:
    #   context: .
    #   target: webhook
    image: puzzlemoondev/bililive-recorder-webhook
    ports:
      - '5555:5555'
      - '9000:9000'
      - '9001:9001'
    networks:
      - recorder_network
    volumes:
      - ./rec:/rec
      - ./action:/action
      - ./biliup:/etc/biliup
      - ./webhook:/etc/webhook
    environment:
      - BAIDUPCS_BDUSS
      - BAIDUPCS_STOKEN
      - ALIYUNPAN_RTOKEN
    restart: always
networks:
  recorder_network:
