services:
  recorder:
    container_name: recorder
    image: bililive/recorder
    ports:
      - "2356:2356"
    networks:
      - recorder_network
    volumes:
      - ./rec:/rec
    restart: always
    command: [
      "run", 
      "--bind", 
      "http://*:2356", 
      "--http-basic-user", 
      "${RECORDER_USER}", 
      "--http-basic-pass",
      "${RECORDER_PASS}",
      "/rec"
    ]
  webhook:
    container_name: webhook
    build: 
      context: .
      dockerfile: webhook.Dockerfile
    ports:
      - "9000:9000"
    networks:
      - recorder_network
    volumes:
      - ./rec:/rec
      - ./webhook:/etc/webhook
    restart: always
    environment:
      - BAIDUPCS_BDUSS
      - BAIDUPCS_STOKEN
      - ALIYUNPAN_RTOKEN
    command: [
      "-verbose", 
      "-hooks=/etc/webhook/hooks.json", 
      "-hotreload"
    ]
networks:
  recorder_network: