services:
  webhook:
    image: puzzlemoondev/bililive-recorder-webhook:latest
    ports:
      - '2356:2356'
      - '5555:5555'
      - '9001:9001'
    volumes:
      - ./rec:/rec
      - ./biliup:/etc/biliup
    environment:
      - RECORDER_USER
      - RECORDER_PASS
      - BAIDUPCS_BDUSS
      - BAIDUPCS_STOKEN
      - ALIYUNPAN_RTOKEN
      - BURN_DANMAKU
      - DANMAKU_FACTORY_ARGS
    restart: always
