name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push webhook
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: puzzlemoondev/bililive-recorder-webhook:latest
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max