name: Publish

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags'
        required: true
        type: string
  workflow_call:
    inputs:
      tags:
        required: true
        type: string

env:
  TAGS: ${{ (inputs || github.event.inputs).tags }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare Tags
        id: tags
        uses: actions/github-script@v6
        env:
          tags: ${{ env.TAGS }}
          separator: ','
          imageName: puzzlemoondev/bililive-recorder-webhook
        with:
          result-encoding: string
          script: |
            const { tags, separator, imageName } = process.env
            return tags
              .replace(/\s+/g, '')
              .split(separator)
              .map((tag) => ''.concat(imageName, ':', tag))
              .join(separator)
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.tags.outputs.result }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
